# Site settings
title: Stephanie Pradier 
email: srrpradier@gmail.com
description: Stephanie's website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stephaniepradier.github.io" # the base hostname & protocol for your site
subtitle: Subtitle # Your description
github_username: stephaniepradier # Your github username
twitter_username: steph_renee
simple_search: http://google.com/search
# Build settings
markdown: kramdown
author: Stephanie Pradier # Your site author
